#INCLUDE "P16F877A.INC"	
	
#DEFINE WAY_1_RED		PORTD, 5
#DEFINE	WAY_1_GREEN 	PORTD, 4

#DEFINE WAY_2_RED		PORTD, 3
#DEFINE	WAY_2_GREEN 	PORTD, 2

#DEFINE WAY_3_RED		PORTD, 1
#DEFINE	WAY_3_GREEN 	PORTD, 0

#DEFINE WAY_4_RED		PORTD, 7
#DEFINE	WAY_4_GREEN 	PORTD, 6

#DEFINE	TRAFFIC			PORTD
#DEFINE SWITCH			PORTC, 0
#DEFINE PB				PORTB, 0

#DEFINE	DISPLAY_PORT	PORTB

CBLOCK 0X20
	A1, A2, A3
	POT_1_VAL, POT_2_VAL, POT_3_VAL, POT_4_VAL, SUM
	DELAY_1, DELAY_2, DELAY_3, DELAY_4, DELAY_13, DELAY_24
	TEMP, MODE
	ENDC


	ORG		0X000
	GOTO	MAIN

	ORG		0X04

	BCF		INTCON, INTF
	MOVLW	B'00000001'
	XORWF	MODE
	RETFIE


MAIN
	CALL	SETUP
	BSF		INTCON, GIE
	BSF		INTCON, INTE
	CALL	SETUP_USART
	CALL	CHECK_POTS
REP
	BTFSS	MODE, 0
	GOTO	REGULAR_MODE
	GOTO	EMERGENCY_MODE


REGULAR_MODE
	BTFSS	SWITCH
	GOTO	SINGLE_MODE
	GOTO	DOUBLE_MODE
	GOTO	REP

EMERGENCY_MODE
	CALL	DISPLAY_E
	BSF		WAY_1_RED
	BSF		WAY_2_RED
	BSF		WAY_3_RED
	BSF		WAY_4_RED

	BCF		WAY_1_GREEN
	BCF		WAY_2_GREEN
	BCF		WAY_3_GREEN
	BCF		WAY_4_GREEN
	CALL	DELAY_1S

	BCF		WAY_1_RED
	BCF		WAY_2_RED
	BCF		WAY_3_RED
	BCF		WAY_4_RED

	BSF		WAY_1_GREEN
	BSF		WAY_2_GREEN
	BSF		WAY_3_GREEN
	BSF		WAY_4_GREEN
	CALL	DELAY_1S

	GOTO	REP
	




CHECK_POTS
	CALL	READ_POT1
	CALL	READ_POT2
	CALL	READ_POT3
	CALL	READ_POT4

RETRY	
	CLRF	SUM
	MOVF	POT_1_VAL, W
	MOVWF	SUM

	MOVF	POT_2_VAL, W
	ADDWF	SUM

	MOVF	POT_3_VAL, W
	ADDWF	SUM

	MOVF	POT_4_VAL, W
	ADDWF	SUM

	CALL	SEND_INFO

	MOVF	SUM, W
	SUBLW	D'10'
	BTFSS	STATUS, C
	GOTO	HIGHER
	GOTO	LOWER

HIGHER


	MOVF	POT_1_VAL, W
	XORLW	D'1'
	BTFSS	STATUS, Z
	DECF	POT_1_VAL, F

	MOVF	POT_2_VAL, W
	XORLW	D'1'
	BTFSS	STATUS, Z
	DECF	POT_2_VAL, F

	MOVF	POT_3_VAL, W
	XORLW	D'1'
	BTFSS	STATUS, Z
	DECF	POT_3_VAL, F

	MOVF	POT_4_VAL, W
	XORLW	D'1'
	BTFSS	STATUS, Z
	DECF	POT_4_VAL, F

	CALL	SEND_INFO
;	CALL	DELAY_1S
	GOTO	RETRY

LOWER

	MOVF	POT_1_VAL, W
	MOVWF	DELAY_1

	MOVF	POT_2_VAL, W
	MOVWF	DELAY_2

	MOVF	POT_3_VAL, W
	MOVWF	DELAY_3

	MOVF	POT_4_VAL, W
	MOVWF	DELAY_4

	RETURN


SEND_INFO
	MOVF	POT_1_VAL, W
	ADDLW	0X30
	MOVWF	TXREG
	CALL	DELAY_10MS

	MOVF	POT_2_VAL, W
	ADDLW	0X30
	MOVWF	TXREG
	CALL	DELAY_10MS

	MOVF	POT_3_VAL, W
	ADDLW	0X30
	MOVWF	TXREG
	CALL	DELAY_10MS

	MOVF	POT_4_VAL, W
	ADDLW	0X30
	MOVWF	TXREG
	CALL	DELAY_10MS

	MOVF	SUM, W
	ADDLW	0X30
	MOVWF	TXREG
	CALL	DELAY_10MS

	MOVLW	D'13'
	MOVWF	TXREG
	CALL	DELAY_10MS
	RETURN

DISPLAY_1
	MOVLW	B'00001100'
	MOVWF	DISPLAY_PORT
	RETURN
	
DISPLAY_2
	MOVLW	B'10110110'
	MOVWF	DISPLAY_PORT
	RETURN

DISPLAY_E
	MOVLW	B'11110010'
	MOVWF	DISPLAY_PORT
	RETURN

SINGLE_MODE
	CALL	DISPLAY_1
	CLRF	TRAFFIC
	BCF		WAY_1_RED
	BSF		WAY_2_RED
	BSF		WAY_3_RED
	BSF		WAY_4_RED
	BSF		WAY_1_GREEN

	MOVF	DELAY_1, W
	CALL	CALCULATED_DELAY
	BCF		WAY_1_GREEN
	BSF		WAY_1_RED
	BCF		WAY_2_RED
	BSF		WAY_3_RED
	BSF		WAY_4_RED
	BSF		WAY_2_GREEN

	MOVF	DELAY_2, W
	CALL	CALCULATED_DELAY
	BCF		WAY_2_GREEN
	BSF		WAY_1_RED
	BSF		WAY_2_RED
	BCF		WAY_3_RED
	BSF		WAY_4_RED
	BSF		WAY_3_GREEN

	MOVF	DELAY_3, W
	CALL	CALCULATED_DELAY
	BCF		WAY_3_GREEN
	BSF		WAY_1_RED
	BSF		WAY_2_RED
	BSF		WAY_3_RED
	BCF		WAY_4_RED
	BSF		WAY_4_GREEN

	MOVF	DELAY_4, W
	CALL	CALCULATED_DELAY
	BCF		WAY_4_GREEN
	GOTO	REP



DOUBLE_MODE
	CALL	DISPLAY_2
	CLRF	TRAFFIC
	BCF		WAY_1_RED
	BSF		WAY_2_RED
	BCF		WAY_3_RED
	BSF		WAY_4_RED
	BSF		WAY_1_GREEN
	BSF		WAY_3_GREEN


	MOVF	DELAY_1, W
	MOVWF	DELAY_13


	MOVF	DELAY_1, W
	SUBWF	DELAY_3, W
	BTFSS	STATUS, C
	GOTO	NEXT1
	MOVF	DELAY_3, W
	MOVWF	DELAY_13


NEXT1
	MOVF	DELAY_13, W
	CALL	CALCULATED_DELAY

	BCF		WAY_1_GREEN
	BCF		WAY_3_GREEN

	BSF		WAY_1_RED
	BCF		WAY_2_RED
	BSF		WAY_3_RED
	BCF		WAY_4_RED
	BSF		WAY_2_GREEN
	BSF		WAY_4_GREEN


	MOVF	DELAY_2, W
	MOVWF	DELAY_24


	MOVF	DELAY_2, W
	SUBWF	DELAY_4, W
	BTFSS	STATUS, C
	GOTO	NEXT2
	MOVF	DELAY_4, W
	MOVWF	DELAY_24


NEXT2
	MOVF	DELAY_24, W
	CALL	CALCULATED_DELAY
	BCF		WAY_2_GREEN
	BCF		WAY_4_GREEN

	GOTO	REP


CALCULATED_DELAY
	MOVWF	TEMP
	CALL	DELAY_1S
	DECFSZ	TEMP, F
	GOTO	$-2
	RETURN

READ_POT1
	MOVLW	B'01000001'
	MOVWF	ADCON0
	CALL	DELAY_20US
	BSF		ADCON0, GO
	BTFSC	ADCON0, GO
	GOTO	$-1
	MOVF	ADRESH, W
	MOVWF	POT_1_VAL
	BCF		STATUS, C
	RRF		POT_1_VAL, F
	BCF		STATUS, C
	RRF		POT_1_VAL, F
	BCF		STATUS, C
	RRF		POT_1_VAL, F
	BCF		STATUS, C
	RRF		POT_1_VAL, F
	BCF		STATUS, C
	RRF		POT_1_VAL, F
	INCF	POT_1_VAL, F
	RETURN

READ_POT2
	MOVLW	B'01001001'
	MOVWF	ADCON0
	CALL	DELAY_20US
	BSF		ADCON0, GO
	BTFSC	ADCON0, GO
	GOTO	$-1
	MOVF	ADRESH, W
	MOVWF	POT_2_VAL
	BCF		STATUS, C
	RRF		POT_2_VAL, F
	BCF		STATUS, C
	RRF		POT_2_VAL, F
	BCF		STATUS, C
	RRF		POT_2_VAL, F
	BCF		STATUS, C
	RRF		POT_2_VAL, F
	BCF		STATUS, C
	RRF		POT_2_VAL, F
	INCF	POT_2_VAL, F
	RETURN

READ_POT3
	MOVLW	B'01010001'
	MOVWF	ADCON0
	CALL	DELAY_20US
	BSF		ADCON0, GO
	BTFSC	ADCON0, GO
	GOTO	$-1
	MOVF	ADRESH, W
	MOVWF	POT_3_VAL
	BCF		STATUS, C
	RRF		POT_3_VAL, F
	BCF		STATUS, C
	RRF		POT_3_VAL, F
	BCF		STATUS, C
	RRF		POT_3_VAL, F
	BCF		STATUS, C
	RRF		POT_3_VAL, F
	BCF		STATUS, C
	RRF		POT_3_VAL, F
	INCF	POT_3_VAL, F
	RETURN

READ_POT4
	MOVLW	B'01011001'
	MOVWF	ADCON0
	CALL	DELAY_20US
	BSF		ADCON0, GO
	BTFSC	ADCON0, GO
	GOTO	$-1
	MOVF	ADRESH, W
	MOVWF	POT_4_VAL
	BCF		STATUS, C
	RRF		POT_4_VAL, F
	BCF		STATUS, C
	RRF		POT_4_VAL, F
	BCF		STATUS, C
	RRF		POT_4_VAL, F
	BCF		STATUS, C
	RRF		POT_4_VAL, F
	BCF		STATUS, C
	RRF		POT_4_VAL, F
	INCF	POT_4_VAL, F
	RETURN

DELAY_20US
	MOVLW	D'5'
	MOVWF	A1
	DECFSZ	A1, F
	GOTO	$-1
	RETURN

DELAY_10MS
    MOVLW    D'1'
    MOVWF    A3
    MOVLW    D'97'
    MOVWF    A2
    MOVLW    D'33'
    MOVWF    A1
    DECFSZ   A1, F
    GOTO     $-1
    DECFSZ   A2, F
    GOTO     $-5
    DECFSZ   A3, F
    GOTO     $-9
    RETURN

SETUP_USART
    BSF 	STATUS, RP0
    BSF 	TRISC, 7
    BCF 	TRISC, 6
    BSF 	PIE1, RCIE
    MOVLW	B'00100100'
    MOVWF	TXSTA
    MOVLW	D'25'
    MOVWF	SPBRG
    BCF 	STATUS, RP0
    MOVLW	B'10010000'
    MOVWF	RCSTA
    BSF 	INTCON, PEIE
    BSF 	INTCON, GIE
    RETURN
SETUP
	CLRF	PORTA
	CLRF	PORTB
	CLRF	PORTC
	CLRF	PORTD
	CLRF	PORTE
	BSF 	STATUS, RP0
	MOVLW	B'00000010'
	MOVWF	ADCON0
	MOVLW	B'00000111'
	MOVWF	CMCON
	MOVLW	B'00001111'
	MOVWF	TRISA
	MOVLW	B'00000001'
	MOVWF	TRISB
	MOVLW	B'00000001'
	MOVWF	TRISC
	MOVLW	B'00000000'
	MOVWF	TRISD
	MOVLW	B'00000000'
	MOVWF	TRISE
	BCF 	STATUS, RP0
	RETURN

DELAY_1S
    MOVLW    D'46'
    MOVWF    A3
    MOVLW    D'189'
    MOVWF    A2
    MOVLW    D'37'
    MOVWF    A1
    DECFSZ   A1, F
    GOTO     $-1
    DECFSZ   A2, F
    GOTO     $-5
    DECFSZ   A3, F
    GOTO     $-9
    RETURN

END
	